# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/annotate/all/annotate.rbi
#
# annotate-2.6.5

module Annotate
  def self.bootstrap_rake; end
  def self.eager_load(options); end
  def self.fallback(*args); end
  def self.load_requires(options); end
  def self.load_tasks; end
  def self.loaded_tasks; end
  def self.loaded_tasks=(val); end
  def self.set_defaults(options = nil); end
  def self.setup_options(options = nil); end
  def self.skip_on_migration?; end
  def self.true?(val); end
  def self.version; end
end
module AnnotateModels
  def self.annotate(klass, file, header, options = nil); end
  def self.annotate_model_file(annotated, file, header, options); end
  def self.annotate_one_file(file_name, info_block, position, options = nil); end
  def self.do_annotations(options = nil); end
  def self.get_index_info(klass, options = nil); end
  def self.get_loaded_model(model_path); end
  def self.get_model_class(file); end
  def self.get_model_files(options); end
  def self.get_schema_info(klass, header, options = nil); end
  def self.model_dir; end
  def self.model_dir=(dir); end
  def self.options_with_position(options, position_in); end
  def self.quote(value); end
  def self.remove_annotation_of_file(file_name); end
  def self.remove_annotations(options = nil); end
  def self.resolve_filename(filename_template, model_name, table_name); end
end
module AnnotateRoutes
  def self.do_annotations(options = nil); end
  def self.remove_annotations(options = nil); end
  def self.routes_exists?; end
  def self.routes_file; end
  def self.strip_annotations(content); end
  def self.strip_on_removal(content, where_header_found); end
  def self.write_contents(content); end
end
