# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rb-fsevent/all/rb-fsevent.rbi
#
# rb-fsevent-0.11.2

module OTNetstring
end
class OTNetstring::Error < StandardError
end
class FSEvent
end
