default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: spotifywrapped_development
  username: <%= ENV.fetch("PGUSER", "grantbingham") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: localhost

test:
  <<: *default
  database: spotifywrapped_test
  username: <%= ENV.fetch("PGUSER", "grantbingham") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: localhost

production:
  <<: *default
  database: <%= ENV["RDS_DB_NAME"] %>
  username: <%= ENV["RDS_USERNAME"] %>
  password: <%= ENV["RDS_PASSWORD"] %>
  host: <%= ENV["RDS_HOSTNAME"] %>
  port: <%= ENV["RDS_PORT"] || 5432 %>

queue:
  <<: *default
  database: <%= ENV["RDS_DB_NAME"] %>
  username: <%= ENV["RDS_USERNAME"] %>
  password: <%= ENV["RDS_PASSWORD"] %>
  host: <%= ENV["RDS_HOSTNAME"] %>
  port: <%= ENV["RDS_PORT"] || 5432 %>

cache:
  <<: *default
  database: <%= ENV["RDS_DB_NAME"] %>
  username: <%= ENV["RDS_USERNAME"] %>
  password: <%= ENV["RDS_PASSWORD"] %>
  host: <%= ENV["RDS_HOSTNAME"] %>
  port: <%= ENV["RDS_PORT"] || 5432 %>
