default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: spotifywrapped_development
  username: <%= ENV.fetch("PGUSER", "grantbingham") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: localhost

test:
  <<: *default
  database: spotifywrapped_test
  username: <%= ENV.fetch("PGUSER", "grantbingham") %>
  password: <%= ENV.fetch("PGPASSWORD", "") %>
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
